name: Sync Backup Branch

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create or Switch to Backup Branch
        run: |
          git checkout -b backup || git checkout backup

      - name: Reset Backup Branch
        run: |
          git fetch origin main
          git reset --hard main~1

      # Needed to workflow permission issues
      - name: Ignore Workflows Folder
        run: |
          echo ".github/workflows/" >> .gitignore
          git add .gitignore
          git commit -m "Ignore workflows folder in backup branch"

      - name: Remove Workflows Folder
        run: |
          if [ -d ".github/workflows" ]; then
            git rm -r --cached .github/workflows
            git commit -m "Remove workflows folder from backup branch"
          fi

      - name: Push Backup Branch
        run: |
          git push origin backup --force