name: Sync Backup Branch

on:
  push:
    branches:
      - main

jobs:
  update-backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create or Switch to Backup Branch
        run: |
          git checkout -b backup || git checkout backup

      - name: Reset Backup Branch
        run: |
          git fetch origin main
          git reset --hard main~1 

      - name: Push Backup Branch
        run: |
          git push origin backup --force